[2023-06-14T01:27:51.949+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_avec_taskflow.bonjour manual__2023-06-14T01:21:46.266295+00:00 [queued]>
[2023-06-14T01:27:51.978+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_avec_taskflow.bonjour manual__2023-06-14T01:21:46.266295+00:00 [queued]>
[2023-06-14T01:27:51.981+0000] {taskinstance.py:1308} INFO - Starting attempt 5 of 10
[2023-06-14T01:27:52.017+0000] {taskinstance.py:1327} INFO - Executing <Task(_PythonDecoratedOperator): bonjour> on 2023-06-14 01:21:46.266295+00:00
[2023-06-14T01:27:52.026+0000] {standard_task_runner.py:57} INFO - Started process 8665 to run task
[2023-06-14T01:27:52.031+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'dag_avec_taskflow', 'bonjour', 'manual__2023-06-14T01:21:46.266295+00:00', '--job-id', '1677', '--raw', '--subdir', 'DAGS_FOLDER/dag_avec_taskflow.py', '--cfg-path', '/tmp/tmpm5wc73gs']
[2023-06-14T01:27:52.034+0000] {standard_task_runner.py:85} INFO - Job 1677: Subtask bonjour
[2023-06-14T01:27:52.158+0000] {task_command.py:410} INFO - Running <TaskInstance: dag_avec_taskflow.bonjour manual__2023-06-14T01:21:46.266295+00:00 [running]> on host 857e1d87a73f
[2023-06-14T01:27:52.354+0000] {abstractoperator.py:597} ERROR - Exception rendering Jinja template for task 'bonjour', field 'op_args'. Template: (XComArg(<Task(_PythonDecoratedOperator): get_name>, 'last_name'), XComArg(<Task(_PythonDecoratedOperator): get_name>, 'first_name'))
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 589, in _do_render_template_fields
    seen_oids,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/template/templater.py", line 162, in render_template
    return tuple(self.render_template(element, context, jinja_env, oids) for element in value)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/template/templater.py", line 162, in <genexpr>
    return tuple(self.render_template(element, context, jinja_env, oids) for element in value)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/template/templater.py", line 158, in render_template
    return value.resolve(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 76, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/xcom_arg.py", line 373, in resolve
    raise XComNotFound(ti.dag_id, task_id, self.key)
airflow.exceptions.XComNotFound: XComArg result from get_name at dag_avec_taskflow with key="last_name" is not found!
[2023-06-14T01:27:52.385+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1407, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1531, in _execute_task_with_callbacks
    task_orig = self.render_templates(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 2179, in render_templates
    original_task.render_template_fields(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 1254, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 76, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 589, in _do_render_template_fields
    seen_oids,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/template/templater.py", line 162, in render_template
    return tuple(self.render_template(element, context, jinja_env, oids) for element in value)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/template/templater.py", line 162, in <genexpr>
    return tuple(self.render_template(element, context, jinja_env, oids) for element in value)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/template/templater.py", line 158, in render_template
    return value.resolve(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 76, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/xcom_arg.py", line 373, in resolve
    raise XComNotFound(ti.dag_id, task_id, self.key)
airflow.exceptions.XComNotFound: XComArg result from get_name at dag_avec_taskflow with key="last_name" is not found!
[2023-06-14T01:27:52.393+0000] {taskinstance.py:1350} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_avec_taskflow, task_id=bonjour, execution_date=20230614T012146, start_date=20230614T012751, end_date=20230614T012752
[2023-06-14T01:27:52.426+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 1677 for task bonjour (XComArg result from get_name at dag_avec_taskflow with key="last_name" is not found!; 8665)
[2023-06-14T01:27:52.465+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-06-14T01:27:52.513+0000] {taskinstance.py:2651} INFO - 0 downstream tasks scheduled from follow-on schedule check
